Credible.Clients/Models/CoursePortalViewModel.cs
using System.Collections.Generic;
using Core.Models;

namespace Credible.Clients.Models
{
    public class CoursePortalViewModel 
    {
        public IEnumerable<Course> Courses { get; set; }
    }

    public class Course
    {
        public int Portal_Id { get; set; }
        public string Portal_Nm { get; set; }
        public int Course_Portal_Id { get; set; }
        public string Course_Portal_Nm { get; set; }
    }
}

Credible.Clients/Models/DetailViewModel.cs

using System.Collections.Generic;
using Core.Models;

namespace Credible.Clients.Models
{
    public class DetailViewModel
    {
        public Portal Portal { get; set; }
        public IEnumerable<CoursePortal> Courses { get; set; }
    }

}

Credible.Clients/Models/PagingListViewModel.cs
using System.Collections.Generic;

namespace Credible.Clients.Models
{
    public class PagingListViewModel<T>
    {
        public PagingListViewModel()
        {
            PagerButtonCount = 5;
            MatchedCount = -1;
        }

        public IEnumerable<T> Items { get; set; }
        public int PageSize { get; set; }
        public int PageIndex { get; set; }
        public int TotalCount { get; set; }
        public int MatchedCount { get; set; }
        public int PagerButtonCount { get; set; }
    }

}

Credible.Clients/Models/PortalViewModel.cs

using System.Collections.Generic;
using Core.Models;

namespace Credible.Clients.Models
{
    public class PortalViewModel
    {
        public IEnumerable<Portal> Portals { get; set; }
        public int Total { get; set; }
    }

}

Credible.Clients/Models/RegistrationViewModel.cs
using System;
using System.Collections.Generic;
using Core.Models;

namespace Credible.Clients.Models
{
    public class RegistrationViewModel
    {
        public int Course_Id { get; set; }
        public string Course_Nm { get; set; }
        public IEnumerable<RegistrationModel> Registrations { get; set; }
    }

    public class RegistrationModel
    {
        public int User_Id { get; set; }
        public string First_Nm { get; set; }
        public string Last_Nm { get; set; }
        public DateTime Registration_Dttm { get; set; }

        public string Registration_Dttm_Formatted
        {
            get { return this.Registration_Dttm.ToShortDateString(); }
        }
    }
}

Credible.Clients/Models/UserViewModel.cs

using System.Collections.Generic;
using Core.Models;

namespace Credible.Clients.Models
{
    public class UserViewModel
    {
        public IEnumerable<User> Users { get; set; }
    }

}

Credible.Clients/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Services;
using Credible.Clients.Filter;
using Credible.Clients.Models;
using Unity.Attributes;

namespace Credible.Clients.Controllers
{
    [UowActionFilter]
    public class ClientController : Controller
    {
        [Dependency]
        public IPortalService PortalService { get; set; }
        [Dependency]
        public ICoursePortalService CoursePortalService { get; set; }
        public ActionResult Index()
        {
            var portals = PortalService.FindAll();
            var vm = new PortalViewModel();
            if (portals != null)
            {
                vm.Portals = portals.ToList();
                vm.Total = portals.Count();
            };
            return View(vm);
        }

        public ActionResult Detail(int id)
        {
            var vm = new DetailViewModel
            {
                Portal = PortalService.GetPortal(id),
                Courses = CoursePortalService.FindAll().Where(x=>x.Portal_Id == id).ToList()
            };
            return View(vm);
        }
    }
}

Credible.Clients/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Services;
using Credible.Clients.Filter;
using Credible.Clients.Models;
using Unity.Attributes;

namespace Credible.Clients.Controllers
{
    [UowActionFilter]
    public class CourseController : Controller
    {
        [Dependency]
        public ICoursePortalService CoursePortalService { get; set; }

        [Dependency]
        public IRegistrationService RegistrationService { get; set; }

        [Dependency]
        public IUserService UserService { get; set; }

        public ActionResult Index()
        {
            var vm = new CoursePortalViewModel
            {
                Courses = CoursePortalService.FindAll()
                    .Select( x=> new Course { Portal_Id = x.Portal_Id, Portal_Nm = x.Portal.Portal_Nm,
                        Course_Portal_Nm = x.Course_Portal_Nm, Course_Portal_Id = x.Course_Portal_Id })
                    .OrderBy(x => x.Portal_Nm).ThenBy(x=>x.Course_Portal_Nm).ToList()
            };
            return View(vm);
        }

        public ActionResult Registrations(int id)
        {
            var course = CoursePortalService.GetCourse(id);
            if (course == null)
            {
                throw new KeyNotFoundException("id");
            }

            var vm = new RegistrationViewModel
            {
                Course_Id = id,
                Course_Nm = course.Course_Portal_Nm,
                Registrations = RegistrationService.FindAll().AsQueryable()
                    .Where(x => x.Course_Portal_Id == id)
                    .Select(x=> new RegistrationModel { User_Id = x.User_Id, First_Nm = x.User.First_Nm, Last_Nm = x.User.Last_Nm, Registration_Dttm = x.Registration_Dttm })
                    .ToList()
            };
            return View(vm);
        }

        public ActionResult Filter(int id, DateTime? startDate, DateTime? endDate)
        {
            var course = CoursePortalService.GetCourse(id);
            if (course == null)
            {
                throw new KeyNotFoundException("id");
            }

            var regs = RegistrationService.FindAll().AsQueryable().Where(x => x.Course_Portal_Id == id);
            if (startDate.HasValue)
            {
                regs = regs.Where(x => x.Registration_Dttm >= startDate.Value);
            }
            if (endDate.HasValue)
            {
                regs = regs.Where(x => x.Registration_Dttm <= endDate.Value);
            }
            var vm = new RegistrationViewModel
            {
                Course_Id = id,
                Course_Nm = course.Course_Portal_Nm,
                Registrations = regs.Select(x => new RegistrationModel { User_Id = x.User_Id, First_Nm = x.User.First_Nm, Last_Nm = x.User.Last_Nm, Registration_Dttm = x.Registration_Dttm })
                    .ToList()
            };
            return PartialView("_FilterPartial", vm);
        }
    }    
   
}

Credible.Clients/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Credible.Clients.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
       
    }
}

Credible.Clients/Views/Client/Detail.cshtml
@model Credible.Clients.Models.DetailViewModel
@{
    ViewBag.Title = "Client Detail";
    var detailUrl = Url.Action("Registrations", "Course");
}

<h2>@ViewBag.Title</h2>
<p>
    <a href="javascript: history.go(-1)"><< Back</a>
</p>
<h3>(@Model.Portal.Portal_Id) @Model.Portal.Portal_Nm</h3>

<table id="listtable" class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Course</th>
        </tr>
    </thead>
    <tbody>
    @if (!Model.Courses.Any())
    {
        <tr>
            <td colspan="2">No record found.</td>
        </tr>
    }
    else
    {
        foreach (var course in Model.Courses)
         {
             <tr title="Click to view registrations" data-id="@course.Course_Portal_Id">
                 <th scope="row">@course.Course_Portal_Id</th>
                 <td>@course.Course_Portal_Nm</td>
             </tr>
         }
    }
</table>

@if (Model.Courses.Any())
{
    <script>
        $(function() {
            $('#listtable tbody tr').hover(function () {
                $(this).addClass('hover-line');
            }, function () {
                $(this).removeClass('hover-line');
            });
            $('#listtable tbody tr').click(function () {
                var url = '@detailUrl';
                var id = $(this).data("id");
                window.location.href = url + "\\" + id;
            });
        })
    </script>
}

Credible.Clients/Views/Client/Index.cshtml
@model Credible.Clients.Models.PortalViewModel
@{
    ViewBag.Title = "Clients";
    var detailUrl = Url.Action("Detail", "Client");
}
<h2>@ViewBag.Title</h2>

<table id="listtable" class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var portal in Model.Portals)
    {
        <tr title="Click to view courses" data-id="@portal.Portal_Id">
            <th scope="row">@portal.Portal_Id</th>
            <td>@portal.Portal_Nm</td>
        </tr>
    }
    @if (!Model.Portals.Any())
    {
        <tr>
            <td colspan="2">No record found.</td>
        </tr>
    }
    </tbody>
</table>
@if (Model.Portals.Any())
{
    <script>
        $(function() {
            $('#listtable tbody tr').hover(function () {
                $(this).addClass('hover-line');
            }, function () {
                $(this).removeClass('hover-line');
            });
            $('#listtable tbody tr').click(function () {
                var url = '@detailUrl';
                var id = $(this).data("id");
                window.location.href = url + "\\" + id;
            });
        })
    </script>
}

Credible.Clients/Views/Course/Index.cshtml
@model Credible.Clients.Models.CoursePortalViewModel
@{
    ViewBag.Title = "Courses";
    var detailUrl = Url.Action("Registrations", "Course");
}
<h2>@ViewBag.Title</h2>

<table id="listtable" class="table">
    <thead>
    <tr>
        <th scope="col">Client #</th>
        <th scope="col">Client Name</th>
        <th scope="col">Course #</th>
        <th scope="col">Course Name</th>
    </tr>
    </thead>
    <tbody>
        @if (!Model.Courses.Any())
        {
            <tr>
                <td colspan="4">No record found.</td>
            </tr>
        }
        else
        {
            foreach (var course in Model.Courses)
            {
                <tr title="Click to view registrations" data-id="@course.Course_Portal_Id">
                    <th scope="row">@course.Portal_Id</th>
                    <td>@course.Portal_Nm</td>
                    <td>@course.Course_Portal_Id</td>
                    <td>@course.Course_Portal_Nm</td>
                </tr>
            }
        }
    </tbody>
</table>

<script>
    $(function() {
        $('#listtable tbody tr').hover(function () {
            $(this).addClass('hover-line');
        }, function () {
            $(this).removeClass('hover-line');
        });
        $('#listtable tbody tr').click(function () {
            var url = '@detailUrl';
            var id = $(this).data("id");
            window.location.href = url + "\\" + id;
        });
    })
</script>

Credible.Clients/Views/Course/Registrations.cshtml
@model Credible.Clients.Models.RegistrationViewModel
@{
    ViewBag.Title = "Course Registrations";
}

<h2>@ViewBag.Title</h2>
<p>
    <a href="javascript: history.go(-1)"><< Back</a>
</p>
<h3>(@Model.Course_Id) @Model.Course_Nm</h3>
<label>Registration Date Range:</label>
<input type="date" id="startDate" name="startDate" />
<input type="date" id="endDate" name="endDate" />
<input type="submit" value="Go" id="btnSubmit" />
<table id="listtable" class="table">
    <thead>
        <tr>
            <th scope="col">User #</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Registration Date</th>
        </tr>
    </thead>
    <tbody id="results">
    @if (!Model.Registrations.Any())
    {
        <tr>
            <td colspan="4">No record found.</td>
        </tr>
    }
    else
    {
        foreach (var course in Model.Registrations)
         {
             <tr>
                 <th scope="row">@course.User_Id</th>
                 <td>@course.First_Nm</td>
                 <td>@course.Last_Nm</td>
                 <td>@course.Registration_Dttm_Formatted</td>
             </tr>
         }
    }
</table>

@if (Model.Registrations.Any())
{
    <script>
        $(function() {
            $('#listtable tbody tr').hover(function () {
                $(this).addClass('hover-line');
            }, function () {
                $(this).removeClass('hover-line');
            });

            $("#btnSubmit").click(function() {
                var startDate = $("#startDate").val();
                var endDate = $("#endDate").val();
                $.ajax({
                    url: '/Course/Filter',
                    type: 'post',
                    data: {
                        id: @Model.Course_Id,
                        startDate: startDate,
                        endDate: endDate
                    },
                    success: function (data) {
                        if (data) {
                            $("#results").html(data);
                        }
                    }
                });
            });
        })
    </script>
}

Credible.Clients/Views/Course/_FilterPartial.cshtml
@model Credible.Clients.Models.RegistrationViewModel


@if (!Model.Registrations.Any())
{
    <tr>
        <td colspan="4">No record found.</td>
    </tr>
}
else
{
    foreach (var course in Model.Registrations)
     {
         <tr>
             <th scope="row">@course.User_Id</th>
             <td>@course.First_Nm</td>
             <td>@course.Last_Nm</td>
             <td>@course.Registration_Dttm_Formatted</td>
         </tr>
     }
}

Credible.Clients/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Credible Developer Test Web Application Project</h1>
    <p class="lead">ASP.NET MVC Web applications using HTML, CSS and JavaScript.</p>
    <p>- Richard D. Miranda.</p>
    <p>@Html.ActionLink("Click to view Client List", "Index", "Client", null, new { @class = "btn btn-primary btn-lg" })</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Requirements</h2>
        <p>Create an ASP.net MVC application that calls to a database to bring back all Clients, client courses, and users taking the courses.</p>
        <ul>
            <li>An end-user can see a list of clients.</li>
            <li>Selecting a client should call to get list of courses for the selected client.</li>
            <li>Selecting a course should bring up list of users registered to the course.</li>
            <li>Display user id, first name, last name, registration date.</li>
        </ul>
        <h3>For extra credit:</h3>
        <ul>
            <li>Enable paging on the list of user registrations – 25 rows per page.</li>
            <li>Allow sorting by all fields on the list of user registrations</li>
            <li>Allow filtering based upon registration date on the list of user registrations</li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>Notes</h2>
        <ul>
            <li>The application is to be built using ASP.net MVC, C # , SQL server database (provided to you)</li>
            <li>Use jquery to handle highlighting alternate rows on the table and making the app as async as possible.</li>
            <li>Application must also make use of a service layer and any other .NET best practices</li>
            <li>Any additional libraries added must be included in the project</li>
            <li>Do not use stored procedures - please write LINQ to SQL / lambda expressions in line.</li>
        </ul>
    </div>
</div>

Credible.Clients/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Clients</title>
    <link rel="Shortcut Icon" href="~/favicon.png" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Credible Developer Test Web Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Clients", "Index", "Client")</li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Courses", "Index", "Course")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Credible Developer Test Web Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>